export const FETCH_ALL_PRODUCTS_PENDING = "FETCH_ALL_PRODUCTS_PENDING";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILED = "FETCH_ALL_PRODUCTS_FAILED";

export const FETCH_ONE_PRODUCT_PENDING = "FETCH_ONE_PRODUCT_PENDING";
export const FETCH_ONE_PRODUCT_SUCCESS = "FETCH_ONE_PRODUCT_SUCCESS";
export const FETCH_ONE_PRODUCT_FAILED = "FETCH_ONE_PRODUCT_FAILED";

export const ADD_PRODUCT_PENDING = "ADD_PRODUCT_PENDING";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const REMOVE_PRODUCT_PENDING = "REMOVE_PRODUCT_PENDING";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAILED = "REMOVE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const BASE_URL = "http://localhost:8000/flower-shop";
