export const FETCH_ALL_FLOWERS_PENDING = "FETCH_ALL_FLOWERS_PENDING";
export const FETCH_ALL_FLOWERS_SUCCESS = "FETCH_ALL_FLOWERS_SUCCESS";
export const FETCH_ALL_FLOWERS_FAILED = "FETCH_ALL_FLOWERS_FAILED";

export const FETCH_ONE_FLOWER_PENDING = "FETCH_ONE_FLOWER_PENDING";
export const FETCH_ONE_FLOWER_SUCCESS = "FETCH_ONE_FLOWER_SUCCESS";
export const FETCH_ONE_FLOWER_FAILED = "FETCH_ONE_FLOWER_FAILED";

export const ADD_FLOWER_PENDING = "ADD_FLOWER_PENDING";
export const ADD_FLOWER_SUCCESS = "ADD_FLOWER_SUCCESS";
export const ADD_FLOWER_FAILED = "ADD_FLOWER_FAILED";

export const REMOVE_FLOWER_PENDING = "REMOVE_FLOWER_PENDING";
export const REMOVE_FLOWER_SUCCESS = "REMOVE_FLOWER_SUCCESS";
export const REMOVE_FLOWER_FAILED = "REMOVE_FLOWER_FAILED";

export const UPDATE_FLOWER_PENDING = "UPDATE_FLOWER_PENDING";
export const UPDATE_FLOWER_SUCCESS = "UPDATE_FLOWER_SUCCESS";
export const UPDATE_FLOWER_FAILED = "UPDATE_FLOWER_FAILED";

export const BASE_URL = "http://localhost:5432/flowers";
